### PR TITLE
Get file and folder metadata for media items using a single network call if possible

### LINKED ISSUE #5045: Initialization of library items of remote storages is really slow
- OctoberCMS Build: 1.0.465
- PHP Version: 7.2
- Database Engine: mysql
- Plugins Installed: _not relevant_

### Description
When opening the media library on an empty cache, the page loads really slow and even timeouts. This is only the case for me when storing media externally, in my case on Google Cloud Storage.  

### Steps To Reproduce
Set up a remote storage and use it for media. Run `artisan cache:clear` and open the media library.

### Proposed fix
By using `$this->getStorageDisk()->listContents($fullFolderPath)` in the MediaLibrary class, we can get the timestamp and size information of all files and folders in 1 network call instead of (in my case) 311 calls. Not only does this really speed up the process, it can also be a lot cheaper if your storage provider makes you pay per call to their API.

The only catch: the [`listContents`](https://flysystem.thephpleague.com/v1/docs/usage/filesystem-api/#list-contents) function returns an array of arrays and the only _required_ metadata is path info and file type. Whether  timestamp and size information is returned is dependant on the adapter implementation. This means that, depending on the used adapter, these extra network calls may still be necessary. Looking at a couple of adapter implementations, all of them seem to provide the required information though:

| Adapter                                                                                                                                                   | Size?  | Timestamp   |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------|--------|-------------|
| [thephpleague/flysystem-aws-s3-v3](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L267)                             | `size` | `timestamp` |
| [Superbalist/flysystem-google-cloud-storage](https://github.com/Superbalist/flysystem-google-cloud-storage/blob/master/src/GoogleStorageAdapter.php#L359) | `size` | `timestamp` |
| [thephpleague/flysystem-rackspace](https://github.com/thephpleague/flysystem-rackspace/blob/master/src/RackspaceAdapter.php#L248)                         | `size` | `timestamp` |

#### Before
- Page load: 47.3s
- Network calls: 311

Screenshot

#### After
- Page load: 3.9s
- Network calls: 14

Screenshot

### PR DESCRIPTION
**Pull request by DieterHolvoet**
Fixes #5045.

### CODE REVIEW

**Comment by mjauvin** [comment]
Please add unit tests in `tests/unit/system/classes/MediaLibrary.php` to validate these changes.

**Comment by LukeTowers** [comment]
Awesome @DieterHolvoet! Are you able to provide some unit testing for this change just to make sure the library is still working fine with the regular local storage option with and without this change?

**Comment by DieterHolvoet** [comment]
Of course, I'll try to do that the coming week.

**Comment by DieterHolvoet** [comment]
I added some basic test coverage for MediaLibrary::listFolderContents. I don't have much experience with testing, so let me know if this does not look right.

**Comment by LukeTowers** [comment]
Seems fine to me. @bennothommo can you review? Once we merge this we'll have to make sure we modify the test when merging it into the L6 branch

File: tests/unit/system/classes/MediaLibraryTest.php [hunk 1]
```diff
@@ -62,4 +68,60 @@ public function testValidPathsOnValidatePath($path)
...
+        $contents = MediaLibrary::instance()->listFolderContents();
+        $this->assertNotEmpty($contents, 'Media library item is not discovered');
+
+        $item = reset($contents);
+        $this->assertAttributeEquals('file', 'type', $item, 'Media library item does not have the right type');
+        $this->assertAttributeEquals('/text.txt', 'path', $item, 'Media library item does not have the right path');
+        $this->assertAttributeNotEmpty('lastModified', $item, 'Media library item last modified is empty');
+        $this->assertAttributeNotEmpty('size', $item, 'Media library item size is empty');
+
+        $this->removeMedia();
```
Comment (bennothommo) [inline tests/unit/system/classes/MediaLibraryTest.php:85]: @DieterHolvoet you will need to make this part of the `tearDown` process in the test class - otherwise, if the test fails, the test files that you had copied over will still be stored on disk.

File: tests/unit/system/classes/MediaLibraryTest.php [hunk 2]
```diff
@@ -62,4 +68,60 @@ public function testValidPathsOnValidatePath($path)
...
+    }
+
+    protected function removeMedia()
+    {
+        foreach (glob(storage_path('app/media/*')) as $file) {
+            unlink($file);
+        }
+
+        rmdir(storage_path('app/media'));
+        rmdir(storage_path('app'));
```
Comment (bennothommo) [inline tests/unit/system/classes/MediaLibraryTest.php:125]: @DieterHolvoet just to clarify, this media removal all happens within your temp storage folder, yes? It doesn't have any effect on the actual media folder?

File: modules/system/classes/MediaLibrary.php [hunk 3]
```diff
@@ -665,17 +669,19 @@ protected function scanFolderContents($fullFolderPath)
...
+                $type = MediaLibraryItem::TYPE_FOLDER;
+                $key = 'folders';
             }
-        }
 
-        $folders = $this->getStorageDisk()->directories($fullFolderPath);
-        foreach ($folders as $folder) {
-            if ($libraryItem = $this->initLibraryItem($folder, MediaLibraryItem::TYPE_FOLDER)) {
-                $result['folders'][] = $libraryItem;
+            if ($libraryItem = $this->initLibraryItem($content, $type)) {
```
Comment (bennothommo) [inline modules/system/classes/MediaLibrary.php:683]: @DieterHolvoet I usually prefer variable assignments to happen before they are used as a condition, as it allows tools like Xdebug to review the variable before it jumps around in the condition statement. (I realise this wasn't your doing - but let's fix it anyways).

```suggestion
            $libraryItem = $this->initLibraryItem($content, $type);
            if (!is_null($libraryItem)) {
```

File: tests/unit/system/classes/MediaLibraryTest.php (hunk 1 above)
Comment (DieterHolvoet) [reply tests/unit/system/classes/MediaLibraryTest.php:85]: Yes, the storage path is changed by calling
```php
$this->app->useStoragePath(base_path('storage/temp'));
```

File: tests/unit/system/classes/MediaLibraryTest.php (hunk 2 above)
Comment (DieterHolvoet) [reply tests/unit/system/classes/MediaLibraryTest.php:125]: Yes, the storage path is changed by calling
```php
$this->app->useStoragePath(base_path('storage/temp'));
```
so there's no effect on the usual media folder.

File: tests/unit/system/classes/MediaLibraryTest.php (hunk 1 above)
Comment (DieterHolvoet) [reply tests/unit/system/classes/MediaLibraryTest.php:85]: This causes errors in the path validation tests. Also, the files will be copied and deleted 26 times because of those path validation tests, which seems a little wasteful. Is it an option to move this new test to a separate class?

Comment (bennothommo) [reply tests/unit/system/classes/MediaLibraryTest.php:85]: @DieterHolvoet Alright, well then the `setupStorage` method should be run only in this test case, and not as part of the `setUp` callback. It's not needed for those other tests.

I'd prefer your new test to be kept in this class as it is testing a part of the MediaLibrary class.

File: tests/unit/system/classes/MediaLibraryTest.php (hunk 2 above)
Comment (DieterHolvoet) [reply tests/unit/system/classes/MediaLibraryTest.php:128]: I added an extra test that makes sure files are only deleted when the storage path is changed.

File: tests/unit/system/classes/MediaLibraryTest.php (hunk 1 above)
Comment (DieterHolvoet) [reply tests/unit/system/classes/MediaLibraryTest.php]: @bennothommo Did the changes, let me know what you think.

Comment (bennothommo) [reply tests/unit/system/classes/MediaLibraryTest.php]: Thanks @DieterHolvoet - looks fine to me.

**Comment by bennothommo** [comment]
@github-actions run

<details>
<summary>✔ Ready for testing</summary>

```js
(async () => {
  // Get issue/PR number
  const number = context.issue.number;

  // Add Testing Needed label
  await githubClient.issues.addLabels({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: number,
    labels: ['Testing Needed'],
  });

  // Comment body
  const commentBody = 'This pull request has been marked as **Ready for Testing**. To expedite this pull request being'
    + ' merged, we encourage members of the community to test the changes and confirm they are working. You may view our'
    + ' [Testing a Pull Request](https://github.com/octobercms/october/blob/develop/.github/CONTRIBUTING.md#testing-a-pull-request)'
    + ' section in the Contibution Guide to access the changes in your own copy of October CMS.'
    + '\n\n'
    + 'If you have [Docker](https://www.docker.com/), you can quickly run a copy of October CMS with this pull request\'s'
    + ' changes in place via the following command:'
    + '\n\n'
    + '```\n'
    + 'docker run --rm -p 80:80 -e GIT_MERGE_PR=' + number + ' aspendigital/octobercms:develop\n'
    + '```';

  // Add comment
  await postComment(commentBody);
})();
```

**Comment by LukeTowers** [comment]
@bennothommo this is all good to go, no breaking changes just a performance improvement?

**Comment by bennothommo** [comment]
@LukeTowers I haven't tested it yet. I don't really have a remote storage instance to test it on. It looks solid in theory, but just wanted to make sure it works before merging.

**Comment by LukeTowers** [comment]
@DieterHolvoet Great job! Tested this and it works fine, and there is a noticeable performance increase for remote storage.
