### PR TITLE
Fix #3415, #4672

### LINKED ISSUE #3415: Custom Form Widgets With AJAX Handlers Won't Work As Expected Inside Repeaters
Adding a custom form widget, with AJAX handlers, inside a repeater should call that handler upon request. However the response throws an SystemException, even if the said custom widget uses the `$this->getEventHandler('onXXX')` method to access the handler.

In my case I was using the select2 to implement a custom "relation" style widget. Below is the partial that does the fetching request:

````html
<select class="form-control jq-select2" id="<?= $id ?>" name="<?= $name ?>">
</select>
<script lang="javascript" type="text/javascript">
	$(document).ready(function () {
		$('select.jq-select2').select2({
			'placeholder': '(Select Item)',
			'minimumInputLength': 3,
			'templateResult' : function (data) {
				if(!data.id) return data.text;
				console.log(data);
				var option = $(data.text);
				return option;
			},
			'ajax': {
				'delay': 500,
				'url': '',
				'dataType': 'json',
				'transport': function (params, success, failure) {
					$.request('<?= $this->getEventHandler('onFetchResultList') ?>',{
						'data' : { 'query' : params.data.term },
						'success' : success,
						'error' : failure
					});
				}
			}
		});
	});
</script>
````

And this ends up in a php function at the back end, in the style of:
````php
public function onFetchResultList() {
	return [
		"results" => $this->forgeQueryResults(strip_tags(input("query")))
	];
}
````
At rendering, I insert the widget inside a data repeater with name `contents_json` and I give it a name `magazine` - for example. In which case `$this->getEventHandler('onFetchResultList')` renders to `formContentsJsonForm1Magazine` when the partial is rendered in the form.

Upon ajax requests, October returns the following exception in the response
> "A widget with class name 'formContentsJsonForm1Magazine' has not been bound to the controller" on line 513 of /domains/example.domain/httpdocs/modules/backend/classes/Controller.php

I imagine that this should not happen under normal circumstances.
___

**For whom it may concern:** A quick workaround to this issue is to add another widget of the same kind at the top level form fields, then give it a name - f.e. `magazine_ajax` and set it to hidden, just to force the controller to load the widget class in the form. Then instead of using the `getEventHandler()` method in the partial, hardcode the name that the controller uses to identify that widget, in the javascript.  For example, the above `$.request` code of the partial would turn to

````javascript
	$.request('formMagazineAjax::onFetchResultList') ?>
````

##### October build
434

### PR DESCRIPTION
**Pull request by LukeTowers**
Handle child FormWidgets making AJAX requests outside of the repeater's form container. Note that this won't pass on the state of the repeater item as it exists on the webpage because that information won't be sent to the server in an AJAX request sent from outside of the repeater's form container unless the FormWidget sending the orphaned request specifically includes that data in their request, in which case the regular handling will kick in and initialize the widget properly. A discussion should be had whether this fix makes sense to be done in the Repeater FormWidget or if we should force FormWidgets to have the responsibility of initializing their parent repeaters if they're going to be making orphaned AJAX requests.

Should fix #3415, #4672.
Related: https://github.com/octoberrain/test-plugin/pull/78

### CODE REVIEW

**Comment by LukeTowers** [comment]
@MartynasJanu This is my proposed solution from the Repeater. I'd like your thoughts (and @bennothommo's thoughts) on handling this from the Repeater instead of forcing the FormWidgets that want to make orphaned AJAX requests to support being in a repeater (orphaned AJAX request means that the AJAX request is sent from an element that is outside of the repeater form, thus does not include any of the fields necessary for the repeater to properly initialize, #4672 would be an example of handling it from the RecordFinder's point of view).

**Comment by bennothommo** [comment]
@LukeTowers I think I tried a fix like that a couple of months back - it works for a single layer of repeater, but as soon as you start talking about nested repeaters, the same issues occur. I think these lines partly form this fix: https://github.com/octobercms/october/blob/355448573479d8fd65dce13f356acaa0a4e8c425/modules/backend/formwidgets/Repeater.php#L243-L246

File: modules/backend/formwidgets/Repeater.php [hunk 1]
```diff
@@ -220,6 +220,21 @@ protected function processItems()
             ? post($this->formField->getName())
             : $this->getLoadValue();
 
+        // Detect when a child widget is trying to run an AJAX handler
+        // outside of the form element that contains all the repeater
+        // fields that would normally be used to identify that case
+        $handler = $this->controller->getAjaxHandler();
+        if (!$this->loaded && starts_with($handler, $this->alias . 'Form')) {
```
Comment (LukeTowers) [inline modules/backend/formwidgets/Repeater.php]: @bennothommo the starts_with() should handle the child repeaters, although I haven't tested.

Comment (LukeTowers) [reply modules/backend/formwidgets/Repeater.php]: @bennothommo tested it, it works perfectly in the child repeater too!

Comment (LukeTowers) [reply modules/backend/formwidgets/Repeater.php]: Perhaps we can revisit the child repeater approach to see if we can simplify it.

Comment (bennothommo) [reply modules/backend/formwidgets/Repeater.php]: @LukeTowers True, but the regex below would only pick up one index, it wouldn't pick up the other indexes. Unless I'm misreading it.

Comment (MartynasJanu) [reply modules/backend/formwidgets/Repeater.php]: @LukeTowers looks good from first glances. Tested with nested Repeaters too. I guess now the question remains, what could this break in some cases? If nothing, I believe this is suitable

Comment (bennothommo) [reply modules/backend/formwidgets/Repeater.php]: @LukeTowers awesome. While I'm sure we can simplify it in places, I'm also hesitant to make too big a change to them after the last fiasco. :P

Comment (MartynasJanu) [reply modules/backend/formwidgets/Repeater.php]: @LukeTowers Since the index is passed on via the headers as the handler name and the Repeater simply extracts the index from it, without making any alterations, it makes it fool-proof in my opinion. I thought maybe if the Repeater had a number of RecordFinders, there could be problems but after testing I realized the key is just about stripping part of a string, so there should be no harm done in any case. My analytical 0.02
