### PR TITLE
Prevent exception when mail templates/layouts are not found

### LINKED ISSUE #513: Problems after different plugin removal
Hi.

This probably has nothing to do with your plugin but the original developer of `mnshankar/oc-subscribe-plugin` doesn't seem to care :-(

Anyhow, after removing aforementioned `mnshankar/oc-subscribe-plugin plugin`, I'm getting an error message each time I scan for new messages in Rainlab Translate plugin:

> InvalidArgumentException: No hint path defined for [serenitynow.subscribe]. in /var/www/html/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:112

The scan, however, is successful. Any ideas on how to get rid of it? I've checked the DB and there are no leftovers of `mnshankar/oc-subscribe-plugin plugin` plugin. The plugin directory is also empty.

Cheers.

### PR DESCRIPTION
**Pull request by mjauvin**
Replaces #5305
Fixes: rainlab/translate-plugin#513

To replicate the problem:
- [Install RainLab.Translate.]
- [Install a plugin that registers mail templates (e.g. RainLab.User).]
- Go to Settings->Mail->Mail templates page (this actually add the registered mail templates to the database).
- Go to Settings->System->Updates & Plugins and disable the `RainLab.User` plugin.
- Go to Settings->Translate->Translate messages page.
- Click on Scan for messages
- Click on Begin scan

### CODE REVIEW

**Comment by mjauvin** [comment]
This had already been done by Sam for MailPartials:
```
diff --git a/modules/system/models/MailPartial.php b/modules/system/models/MailPartial.php
index 09c38aeb..d0295e06 100644
--- a/modules/system/models/MailPartial.php
+++ b/modules/system/models/MailPartial.php
@@ -8,6 +8,7 @@ use Markdown;
 use System\Classes\MailManager;
 use October\Rain\Mail\MailParser;
 use ApplicationException;
+use Exception;
 
 /**
  * Mail partial
@@ -50,6 +51,22 @@ class MailPartial extends Model
         }
     }
 
+    public static function findOrMakePartial($code)
+    {
+        try {
+            if (!$template = self::whereCode($code)->first()) {
+                $template = new self;
+                $template->code = $code;
+                $template->fillFromCode($code);
+            }
+
+            return $template;
+        }
+        catch (Exception $ex) {
+            return null;
+        }
+    }
+
     /**
      * Loops over each mail layout and ensures the system has a layout,
      * if the layout does not exist, it will create one.
```

File: modules/system/models/MailTemplate.php [hunk 1]
```diff
@@ -68,7 +69,12 @@ public static function allTemplates()
         $codes = array_keys(self::listAllTemplates());
 
         foreach ($codes as $code) {
-            $result[] = self::findOrMakeTemplate($code);
+            try {
+                $result[] = self::findOrMakeTemplate($code);
+            }
+            catch (InvalidArgumentException $e) {
```
Comment (LukeTowers) [inline modules/system/models/MailTemplate.php]: Does view::exists() throw this exception?

Comment (mjauvin) [reply modules/system/models/MailTemplate.php]: Also `self::whereCode()` and `fillFromView()` @LukeTowers

Comment (mjauvin) [reply modules/system/models/MailTemplate.php:75]: > Also `self::whereCode()` @LukeTowers

Comment (mjauvin) [reply modules/system/models/MailTemplate.php]: Actually, `View::exists($code)` does NOT throw the exception @LukeTowers .

Comment (LukeTowers) [reply modules/system/models/MailTemplate.php]: So do we need this try catch block?

Comment (mjauvin) [reply modules/system/models/MailTemplate.php]: Yes we do, that's how we can skip the templates that have been orphaned.

Comment (LukeTowers) [reply modules/system/models/MailTemplate.php]: What throws that exception?

Comment (mjauvin) [reply modules/system/models/MailTemplate.php]: @LukeTowers If you mean the origin of the throw (vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php line 112):
```
if (! isset($this->hints[$segments[0]])) {
   throw new InvalidArgumentException("No hint path defined for [{$segments[0]}].");
}
```

If you mean the call within MailTemplate that leads to the throw, that would be `self::whereCode()` in:
```
    public static function findOrMakeTemplate($code)
    {   
        $template = self::whereCode($code)->first();

        if (!$template && View::exists($code)) {
            $template = new self;
            $template->code = $code;
            $template->fillFromView($code);
        }

        return $template;
    }
```

Comment (mjauvin) [reply modules/system/models/MailTemplate.php]: I couldn't find the definition of the `whereCode()` method anywhere... any idea?

Comment (LukeTowers) [reply modules/system/models/MailTemplate.php]: It's little known shorthand for `where('code', $value)` implemented in the Laravel Query builder. What's the stack trace of the exception?

Comment (mjauvin) [reply modules/system/models/MailTemplate.php]:
```
[2020-10-20 16:10:27] dev.ERROR: InvalidArgumentException: No hint path defined for [offline.mall]. in /home/r4l/public_html/vendor/laravel/framework/src/Illu
minate/View/FileViewFinder.php:112
Stack trace:
#0 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(90): Illuminate\View\FileViewFinder->parseNamespaceSegments('offline.
mall::m...')
#1 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findNamespacedView('offline.mall
::m...')
#2 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/View/Factory.php(131): Illuminate\View\FileViewFinder->find('offline.mall::m...')
#3 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\View\Factory->make('offline.mall::m...')
#4 /home/r4l/public_html/modules/system/models/MailTemplate.php(155): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#5 /home/r4l/public_html/modules/system/models/MailTemplate.php(140): System\Models\MailTemplate::getTemplateSections('offline.mall::m...')
#6 /home/r4l/public_html/modules/system/models/MailTemplate.php(129): System\Models\MailTemplate->fillFromView('offline.mall::m...')
#7 /home/r4l/public_html/vendor/october/rain/src/Database/Model.php(168): System\Models\MailTemplate->afterFetch()
#8 /home/r4l/public_html/vendor/october/rain/src/Events/Dispatcher.php(417): October\Rain\Database\Model->October\Rain\Database\{closure}(Object(System\Models
\MailTemplate))
#9 /home/r4l/public_html/vendor/october/rain/src/Events/Dispatcher.php(260): October\Rain\Events\Dispatcher->October\Rain\Events\{closure}('eloquent.fetche...
', Array)
#10 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(189): October\Rain\Events\Dispatcher->dispatch('elo
quent.fetche...', Array)
#11 /home/r4l/public_html/vendor/october/rain/src/Database/Model.php(444): Illuminate\Database\Eloquent\Model->fireModelEvent('fetched', false)
#12 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(322): October\Rain\Database\Model->newFromBuilder(Object(stdCl
ass))
#13 [internal function]: Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(stdClass))
#14 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(323): array_map(Object(Closure), Array)
#15 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->hydrate(Array)
#16 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1622): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(October\Rain\Database\Builder), 'hydrate', Array)
#17 /home/r4l/public_html/vendor/october/rain/src/Extension/ExtendableTrait.php(428): Illuminate\Database\Eloquent\Model->__call('hydrate', Array)
#18 /home/r4l/public_html/vendor/october/rain/src/Database/Model.php(650): October\Rain\Database\Model->extendableCall('hydrate', Array)
#19 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(545): October\Rain\Database\Model->__call('hydrate', Array)
#20 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(529): Illuminate\Database\Eloquent\Builder->getModels(Array)
#21 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(143): Illuminate\Database\Eloquent\Builder->get(Array)
#22 /home/r4l/public_html/modules/system/models/MailTemplate.php(160): Illuminate\Database\Eloquent\Builder->first()
#23 /home/r4l/public_html/modules/system/models/MailTemplate.php(77): System\Models\MailTemplate::findOrMakeTemplate('offline.mall::m...')
#24 /home/r4l/public_html/plugins/rainlab/translate/classes/ThemeScanner.php(125): System\Models\MailTemplate::allTemplates()
#25 /home/r4l/public_html/plugins/rainlab/translate/classes/ThemeScanner.php(56): RainLab\Translate\Classes\ThemeScanner->scanMailTemplatesForMessages()
#26 /home/r4l/public_html/plugins/rainlab/translate/classes/ThemeScanner.php(28): RainLab\Translate\Classes\ThemeScanner->scanForMessages()
#27 /home/r4l/public_html/plugins/rainlab/translate/controllers/Messages.php(76): RainLab\Translate\Classes\ThemeScanner::scan()
#28 [internal function]: RainLab\Translate\Controllers\Messages->onScanMessages()
#29 /home/r4l/public_html/modules/backend/classes/Controller.php(628): call_user_func_array(Array, Array)
#30 /home/r4l/public_html/modules/backend/classes/Controller.php(478): Backend\Classes\Controller->runAjaxHandler('onScanMessages')
#31 /home/r4l/public_html/modules/backend/classes/Controller.php(277): Backend\Classes\Controller->execAjaxHandlers()
#32 /home/r4l/public_html/modules/backend/classes/BackendController.php(165): Backend\Classes\Controller->run('index', Array)
#33 [internal function]: Backend\Classes\BackendController->run('rainlab/transla...')
#34 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#35 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#36 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#37 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#38 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#39 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /home/r4l/public_html/modules/backend/classes/BackendController.php(68): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(153): Backend\Classes\BackendController->Backend\Classes\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) 
#46 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(:
Object(Illuminate\Http\Request), Object(Closure))
#50 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#55 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#56 /home/r4l/public_html/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) 
#57 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request)) 
#58 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#59 /home/r4l/public_html/plugins/rainlab/debugbar/middleware/InjectDebugbar.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) 
#60 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): RainLab\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure)) 
#61 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) 
#62 /home/r4l/public_html/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(25): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)) 
#63 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)) 
#64 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) 
#65 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#66 /home/r4l/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#67 /home/r4l/public_html/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) 
#68 {main}  
```

Comment (mjauvin) [reply modules/system/models/MailTemplate.php]: Looks like what's actually causing the exception is the fillFromView() call in `MailTemplate::afterFetch()`

So a try/catch around this call would do the trick.

Comment (mjauvin) [reply modules/system/models/MailTemplate.php]: And ultimately, the call that causes this in View::make() in getTemplateSections()... so this is another fix:
```
    protected static function getTemplateSections($code)
    {   
        try { 
            $view = View::make($code);
            return MailParser::parse(FileHelper::get($view->getPath()));
        }
        catch (\Exception $e) {
            return null;
        }
    }       
```

File: modules/system/models/MailLayout.php [hunk 2]
```diff
@@ -152,6 +152,12 @@ public function fillFromView($path)
...
     protected static function getTemplateSections($code)
     {
-        return MailParser::parse(FileHelper::get(View::make($code)->getPath()));
+        try {
+            $view = View::make($code);
+            return MailParser::parse(FileHelper::get($view->getPath()));
+        }
+        catch (InvalidArgumentException $e) {
+            return null;
+        }
```
Comment (LukeTowers) [inline modules/system/models/MailLayout.php:200]: Would probably be simpler to just check if the view exists first. Are the consumers of this method going to fail if they encounter null instead of an array?

Comment (mjauvin) [reply modules/system/models/MailLayout.php:200]: Yeah, I'm addressing this in next commit.

File: modules/system/models/MailLayout.php [hunk 3]
```diff
@@ -80,7 +80,6 @@ public static function findOrMakeLayout($code)
             $layout->code = $code;
             $layout->fillFromView($code);
         }
-
```
Comment (LukeTowers) [inline modules/system/models/MailLayout.php]: Restore this line of whitespace please to match the other methods, plus I like it better formatted like that 😉

**Comment by LukeTowers** [comment]
Looking like some good progress on this @mjauvin, I feel a lot more comfortable with this approach. Would you be willing to add in docblocks for these classes while you're at it?

File: modules/system/models/MailLayout.php (hunk 3 above)
Comment (mjauvin) [reply modules/system/models/MailLayout.php]: that was done by mistake.

**Comment by bennothommo** [comment]
@mjauvin I've converted this to a draft - when it's ready for review, feel free to hit the Ready for review button above :)

**Comment by mjauvin** [comment]
I didn't add the docblocks on the other models yet (MailLayout & MailPartial). I'll do this once the review is done for MailTemplate docblocks.

File: modules/system/models/MailTemplate.php [hunk 4]
```diff
@@ -117,38 +119,71 @@ public static function syncAll()
         }
     }
 
+    /**
+     * Fired after the model has been fetched.
+     * @return void
```
Comment (LukeTowers) [inline modules/system/models/MailTemplate.php]: We're aiming for an empty line between the method description and the rest of the docblock on every method.
```suggestion
     * Fired after the model has been fetched.
     *
     * @return void
```

**Comment by mjauvin** [comment]
To test this PR, use the replication procedure in PR description above. 

You can confirm the bug on the instance below:
[Unpatched-test-instance](https://764707c05ebc.octodock.com/backend)

And confirm the PR resolves the issue on the instance below:
[patched-test-instance](https://d6e37bfe458e.octodock.com/backend)

Note: the first two items in the procedure are already **done** in the test instances.

**Comment by mjauvin** [comment]
I've tested this extensively with the octodock instances [above](https://github.com/octobercms/october/pull/5322#issuecomment-714456460), can we move forward with this or can someone else test this using the provided procedure/test instances?

Thanks.

**Comment by LukeTowers** [comment]
Tried testing with the instances, was unable to replicate original issue. May need to try again later.

**Comment by mjauvin** [comment]
@LukeTowers either you used the wrong instance or you didn't exactly follow the procedure to reproduce. I just tried it and I was able to reproduce.

**Comment by LukeTowers** [comment]
@mjauvin probably, it was pretty late at night when I tried. Is this an urgent issue?

**Comment by mjauvin** [comment]
No, nothing is urgent here.

File: modules/system/models/MailLayout.php [hunk 5]
```diff
@@ -50,13 +50,23 @@ class MailLayout extends Model
...
+     */
     public function beforeDelete()
     {
         if ($this->is_locked) {
             throw new ApplicationException('Cannot delete this template because it is locked');
         }
     }
 
+    /**
+     * List MailLayouts codes keyed by id.
```
Comment (bennothommo) [inline modules/system/models/MailLayout.php]:
```suggestion
     * List MailLayouts codes keyed by ID.
```

File: modules/system/models/MailLayout.php [hunk 6]
```diff
@@ -66,11 +76,24 @@ public static function listCodes()
         return self::$codeCache = self::lists('id', 'code');
     }
 
+    /**
+     * Return the id of a MailLayout searched by its code.
```
Comment (bennothommo) [inline modules/system/models/MailLayout.php]:
```suggestion
     * Return the ID of a MailLayout instance from a defined code.
```

File: modules/system/models/MailLayout.php [hunk 7]
```diff
@@ -66,11 +76,24 @@ public static function listCodes()
...
+     * @return string
+     */
     public static function getIdFromCode($code)
     {
         return array_get(self::listCodes(), $code);
     }
 
+    /**
+     * Find a MailLayout by its code or create a new
+     * one from the view file.
```
Comment (bennothommo) [inline modules/system/models/MailLayout.php]:
```suggestion
     * Find a MailLayout instance by its code or create a new instance from the view file.
```

File: modules/system/models/MailLayout.php [hunk 8]
```diff
@@ -107,6 +131,12 @@ public static function createLayouts()
         }
     }
 
+    /**
+     * Fill model using a view file retrieved by code.
+     *
+     * @param string $code
```
Comment (bennothommo) [inline modules/system/models/MailLayout.php]:
```suggestion
     * @param string|null $code
```

File: modules/system/models/MailLayout.php [hunk 9]
```diff
@@ -50,13 +50,23 @@ class MailLayout extends Model
 
     public static $codeCache;
 
+    /**
+     * Fired before the model is deleted.
+     *
+     * @return void
```
Comment (bennothommo) [inline modules/system/models/MailLayout.php:56]:
```suggestion
     * @return void
     * @throws ApplicationException if the template is locked
```

File: modules/system/models/MailLayout.php [hunk 10]
```diff
@@ -107,6 +131,12 @@ public static function createLayouts()
         }
     }
 
+    /**
+     * Fill model using a view file retrieved by code.
+     *
+     * @param string $code
+     * @return void
```
Comment (bennothommo) [inline modules/system/models/MailLayout.php:138]:
```suggestion
     * @return void
     * @throws ApplicationException if a layout with the defined code is not registered.
```

File: modules/system/models/MailPartial.php [hunk 11]
```diff
@@ -42,13 +42,24 @@ class MailPartial extends Model
...
+     */
     public function afterFetch()
     {
         if (!$this->is_custom) {
             $this->fillFromCode();
         }
     }
 
+    /**
+     * Find a MailPartial record by code or create one from a view file.
```
Comment (bennothommo) [inline modules/system/models/MailPartial.php]:
```suggestion
     * Find a MailPartial instance by code or create a new instance from a view file.
```

File: modules/system/models/MailPartial.php [hunk 12]
```diff
@@ -42,13 +42,24 @@ class MailPartial extends Model
...
+     *
+     * @param string $code
+     * @return MailTemplate model
```
Comment (bennothommo) [inline modules/system/models/MailPartial.php]:
```suggestion
     * @return MailTemplate
```

File: modules/system/models/MailPartial.php [hunk 13]
```diff
@@ -98,6 +110,12 @@ public static function createPartials()
         }
     }
 
+    /**
+     * Fill model using a view file retrieved by code.
+     *
+     * @param string $code
```
Comment (bennothommo) [inline modules/system/models/MailPartial.php]:
```suggestion
     * @param string|null $code
```

**Comment by bennothommo** [comment]
@mjauvin @LukeTowers I've replicated the issue, and confirm that this PR fixes it.
