### PR TITLE
Defer plugin installs from cli advanced step until October is installed

### LINKED ISSUE #4155: Console install: choosing to install October.Drivers and/or RainLab.Builder fails
- OctoberCMS Build: b39eb03336faf4c30ddb059e1973eb313dbd68f6 (dev-develop)
- PHP Version: 7.2
- Database Engine: mysql
- Plugins Installed: None

### Description:
When installing via CLI command, if you choose yes to `Configure advanced options? (yes/no)` there are two questions that allows you to install Rainlab.Builder and October.Drivers in the process. This was made by me (https://github.com/octobercms/october/pull/2974) in 2017 and merged in 2018. But maybe in the meantime something changed, because if you choose yes to any of those, the command fails instantly:

```  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fresh.system_settings' doesn't exist (
  SQL: select * from `system_settings` where `item` = system_log_settings limit 1)



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fresh.system_settings' doesn't exist



  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fresh.system_settings' doesn't exist
```

### Steps To Reproduce:
1. Download a fresh october repo
2. Run ```php artisan october install```
3. When asked `Configure advanced options? (yes/no)` choose yes (`y`)
4. When asked `Install the October.Drivers plugin? (yes/no) [no]:` choose yes
5. Command fails.

### PR DESCRIPTION
**Pull request by filipac**
Fixes #4155

Read about the problem here: https://github.com/octobercms/october/issues/4155
The following code was introduced here: https://github.com/octobercms/october/pull/2974 but it worked back then.

What I did was to return a list of plugin codes from `askToInstallPlugins` function instead of trying to install them right away, then after `setupMigrateDatabase` function is called, loop over the returned array and install the plugins the user chose.

The output then is:
```
Seeded System
Seeded Backend
Installing plugin October.Drivers
October.Drivers installed successfully.
Installing plugin Rainlab.Builder
Rainlab.Builder installed successfully.
```

### CODE REVIEW

File: modules/system/console/OctoberInstall.php [hunk 1]
```diff
@@ -71,16 +71,27 @@ public function handle()
...
-            $this->askToInstallPlugins();
+            $chosenToInstall = $this->askToInstallPlugins();
         }
         else {
             $this->setupEncryptionKey(true);
         }
 
         $this->setupMigrateDatabase();
+
+        foreach($chosenToInstall as $pluginCode) {
```
Comment (LukeTowers) [inline modules/system/console/OctoberInstall.php]: space after foreach before (

File: modules/system/console/OctoberInstall.php [hunk 2]
```diff
@@ -71,16 +71,27 @@ public function handle()
...
+            $this->output->writeln('<info>Installing plugin '.$pluginCode.'</info>');
```
Comment (LukeTowers) [inline modules/system/console/OctoberInstall.php]: spaces on both sides of the string concatenation operator `.` should be ` . `

File: modules/system/console/OctoberInstall.php [hunk 3]
```diff
@@ -71,16 +71,27 @@ public function handle()
...
+            $this->callSilent('plugin:install', [
+                'name' => $pluginCode
+            ]);
+            $this->output->writeln('<info>'.$pluginCode.' installed successfully.</info>');
```
Comment (LukeTowers) [inline modules/system/console/OctoberInstall.php]: spaces string concatenation operator

File: modules/system/console/OctoberInstall.php [hunk 4]
```diff
@@ -120,20 +131,14 @@ protected function setupAdvancedValues()
...
+        $chosenToInstall = [];
         if ($this->confirm('Install the October.Drivers plugin?', false)) {
-            $this->output->writeln('<info>Installing plugin October.Drivers</info>');
-            $this->callSilent('plugin:install', [
-                'name' => 'October.Drivers'
-            ]);
-            $this->output->writeln('<info>October.Drivers installed successfully.</info>');
+            $chosenToInstall[] = 'October.Drivers';
         }
         if($this->confirm('Install the Rainlab.Builder plugin?', false)) {
```
Comment (w20k) [inline modules/system/console/OctoberInstall.php]: Space after `if`.

**Comment by filipac** [comment]
Done. A service like StyleCI should be useful :D

**Comment by w20k** [comment]
@filipac but if it would be free, that'd be something to consider :)

**Comment by w20k** [comment]
@filipac travicCI would do the trick :)

**Comment by LukeTowers** [comment]
@filipac I was just thinking that to myself ;) Just have to find the time to implement it.

@w20k is this good to go?

**Comment by w20k** [comment]
@LukeTowers - yep, all good!
I might test travisCI build with php_codesniffer :) Might do the trick.

**Comment by filipac** [comment]
@w20k @LukeTowers https://prettyci.com/

**Comment by w20k** [comment]
@filipac do you have configs for `prettyci.com` ? I've tried it with a dummy PR, based on your commit, and it's like hell 😄 
https://github.com/w20k/october/pull/3/checks?check_run_id=69747010
